apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-gitops
  template:
    metadata:
      labels:
        app: demo-gitops
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-gitops
spec:
  type: LoadBalancer
  selector:
    app: demo-gitops
  ports:
    - port: 80
      targetPort: 80
