apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-gitops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-gitops
  template:
    metadata:
      labels:
        app: demo-gitops
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-gitops
spec:
  selector:
    app: demo-gitops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP