apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-gitops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-gitops
  template:
    metadata:
      labels:
        app: demo-gitops
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
      resources:
            requests:
              memory: "64Mi"  # Reserva mínima garantizada
              cpu: "100m"     # 10% de un núcleo (0.1 CPU)
            limits:
              memory: "128Mi" # Tope máximo (si pasa, se reinicia)
              cpu: "200m"     # Tope máximo (si pasa, va lento)
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-gitops
spec:
  type: LoadBalancer
  selector:
    app: demo-gitops
  ports:
    - port: 80
      targetPort: 80
